spring:
  application:
    name: "zuca-bot"
  datasource:
    url: jdbc:oracle:thin:@zucadb_high?TNS_ADMIN=src/main/resources/wallet
    username: ${ORA_USERNAME}
    password: ${ORA_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver
    poolName: Ora-Dev
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

secret:
  discord-token: ${DISCORD_APPLICATION_TOKEN}
  football-api-token: ${FOOTBALL_API_TOKEN}