name: Deploy Automático no Oracle Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checar o Repositório
        uses: actions/checkout@v3

      - name: Configurar Chave SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          cat >>~/.ssh/config <<END
          Host oracle-server
            HostName 136.248.88.128
            User ubuntu
            IdentityFile ~/.ssh/deploy_key
            StrictHostKeyChecking no
          END

      - name: Conectar ao Servidor e Atualizar Código
        run: |
          ssh oracle-server << 'EOF'
            cd ~/zuca-bot
            git fetch origin main
            git reset --hard origin/main
            # Força o uso do JDK 24 no servidor também
            sdk use java 24-tem
            mvn clean package -DskipTests
            docker build -t zuca-bot .
            docker stop zuca-bot-container || true
            docker rm zuca-bot-container || true
            docker run --env-file .env -d --name zuca-bot-container -p 8080:8080 --restart always zuca-bot
          EOF
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2-
