name: Deploy Automático no Oracle Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checar o Repositório
        uses: actions/checkout@v3

      - name: Configurar Chave SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          cat >>~/.ssh/config <<END
          Host oracle-server
            HostName 136.248.88.128
            User ubuntu
            IdentityFile ~/.ssh/deploy_key
            StrictHostKeyChecking no
          END

      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.9

      - name: Conectar ao Servidor e Atualizar Código
        run: |
          ssh oracle-server << 'EOF'
            export SDKMAN_DIR="$HOME/.sdkman"
            source "$SDKMAN_DIR/bin/sdkman-init.sh"
            sdk use java 21.0.6-tem
            export JAVA_HOME="$SDKMAN_DIR/candidates/java/current"
            export PATH="$JAVA_HOME/bin:$PATH"

            java -version
            mvn -v

            cd ~/zuca-bot
            git fetch origin main
            git merge --no-commit --no-ff origin/main --allow-unrelated-histories
            git checkout --ours .
            git add .
            git commit -m 'Merge from GitHub main branch' || echo 'No changes to merge'

            mvn clean package -DskipTests

            docker build -t zuca-bot .
            docker stop zuca-bot-container || true
            docker rm zuca-bot-container || true
            docker run --env-file .env -d --name zuca-bot-container -p 8080:8080 --restart always zuca-bot
          EOF

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2-
