name: Deploy Automático no Oracle Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checar o Repositório
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - name: Conectar ao Servidor e Atualizar Código
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@136.248.88.128 << 'EOF'
            cd ~/zuca-bot
            git pull origin main
            mvn clean package -DskipTests
            docker build -t zuca-bot .
            docker stop zuca-bot-container || true
            docker rm zuca-bot-container || true
            docker run --env-file .env -d --name zuca-bot-container -p 8080:8080 --restart always zuca
          EOF
